sudo: required

services:
  - docker

language: java

jdk:
  - openjdk8

before_install:
  - ./gradlew --version
  - docker --version
  - docker-compose --version

script:  
  - ./gradlew check
  - ./gradlew docker
  - docker-compose up -d rabbitmq-server
  - docker-compose up -d config-server
  - sleep 100
  - docker-compose up -d --scale hello-sub-service=2 hello-sub-service
  - sleep 30
  - docker-compose up -d --scale hello-service=2 hello-service
  - sleep 30
  - docker-compose up -d gateway
  - i=0 && until ( test "200" -eq "$(curl --write-out %{http_code} --silent --output /dev/null http://localhost:8081/hello)" ) || ( test "100" -eq "$i" ); do let i=i+1; echo $i - waiting for server up; sleep 10; done && test $i -lt 100

after_success:
  - docker-compose down