spring.application.name: HelloService

server.port: 9001

# Having spring-cloud-starter-netflix-eureka-client on the classpath
# makes the app into both a Eureka “instance” (that is, it registers itself)
# and a “client” (it can query the registry to locate other services).
# The instance behaviour is driven by eureka.instance.* configuration keys,
# but the defaults are fine if you ensure that your application has a value
# for spring.application.name (this is the default for the Eureka service ID or VIP).

# See EurekaInstanceConfigBean and EurekaClientConfigBean for more details
# on the configurable options.

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# expose /hystrix.stream endpoint
management.endpoints.web.exposure.include: hystrix.stream, health, info
