kind: Service
apiVersion: v1
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: gateway
  selector:
    app: gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: redtankd/gateway:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8081
      initContainers:
        - name: init-config-server
          image: byrnedo/alpine-curl
          command: ['sh', '-c', 'until [ "200" -eq $(curl --write-out %{http_code} --silent --output /dev/null http://config-server:8888/actuator/info) ];  do echo waiting for config-server; sleep 2; done']