spring:
  application:
    name: HelloWorld
  cloud:
    zookeeper:
      discovery:
        enabled: true
server:
  port: 8081
logging:
  level:
    root: INFO
    org.apache.zookeeper.ClientCnxn: WARN