spring:
  profiles:
    active: native # native path for configuration
  application:
      name: StandaloneGitServerApplication
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: the default is classpath

server:
  port: 8888 # The port on which this application runs

# see spring-boot's reference: Appendix A. Common application properties
endpoints:
  default.web.enabled: true
  health.enabled: true
  env.enabled: true

logging.level:
  root: INFO
