spring:
  application:
    name: GatewayNode
  cloud:
    config:
      allowOverride: true
      overrideNone: true
    zookeeper:
      discovery:
        enabled: true

server:
  port: 8080

endpoints:
  default.web.enabled: true
  health.enabled: true
  env.enabled: true

logging:
  level:
    root: INFO
    org.apache.zookeeper.ClientCnxn: WARN

gateway:
  property1: 10
  name: default