spring:
  application:
    name: RequestForQuoteServiceNode
  cloud:
    config:
      allowOverride: true
      overrideNone: true
    zookeeper:
      discovery:
        enabled: true

server:
  port: 0

endpoints:
  default.web.enabled: true
  health.enabled: true
  env.enabled: true

logging.level:
  root: INFO
  org.apache.zookeeper.ClientCnxn: WARN

service:
  server:
    port:
      min: 8082
      max: 8083